from pathlib import Path
from typing import Protocol
class Workspace(Protocol):
    @property
    def root(self) -> Path: ...
    def resolve_path(self, relative_path: str) -> Path: ...
    async def list_files(self, path: str = ".", recursive: bool = False, max_entries: int = 200): ...
    async def read_file(self, path: str, start_line: int | None = None, end_line: int | None = None): ...
    async def search_text(self, query: str, path: str = ".", glob: str | None = None, max_matches: int = 100, context_lines: int = 1): ...
